### PR TITLE
detailCalloutAccessoryView

### PR DESCRIPTION
**Pull request by RomanPodymov**
Hello.
Thank you for Map.
Added `detailCalloutAccessoryView`.

### CODE REVIEW

**Comment by pauljohanneskraft** [comment]
Thank you very much for your contribution!

I would love to have a solution without the use of `AnyView` actually, but this would simply be a bit of rewriting (e.g. making a generic constraint on MapPin and then using `EmptyView` as a default value, if there is no view associated with it). 

In this PR, you seem to only add a detailCalloutAccessoryView to MapPin, is there a specific reason for that?

**Comment by RomanPodymov** [comment]
> Thank you very much for your contribution!
> 
> I would love to have a solution without the use of `AnyView` actually, but this would simply be a bit of rewriting (e.g. making a generic constraint on MapPin and then using `EmptyView` as a default value, if there is no view associated with it). I see that even your initial implementation made use of that - is there a reason on why you switched to AnyView?
> 
> In this PR, you seem to only add a detailCalloutAccessoryView to MapPin, is there a specific reason for that?

Hello @pauljohanneskraft 
`AnyView` was sufficient for my project, that's why I use it. But I can add a generic type for `detailCalloutAccessoryView`. And I use `MapPin` only, but I can add this feature to the other annotations.

**Comment by pauljohanneskraft** [comment]
That would both be perfect - thank you very much 😊

**Comment by RomanPodymov** [comment]
> That would both be perfect - thank you very much 😊

Done.

**Comment by RomanPodymov** [comment]
Hello @pauljohanneskraft 
Any updates?

**Comment by pauljohanneskraft** [comment]
Sorry for not responding - I will merge it into another branch, make some adaptions and then release it in the coming days (or maybe I'm finished earlier, not sure yet).

**Pull request merged**
